sudo: required
dist: xenial
language: c
compiler: clang
cache: ccache
git:
  submodules: false

install:
- sudo apt-get install cmake clang bison flex xz-utils libfuse-dev libudev-dev pkg-config linux-headers-generic build-essential flex libelf-dev libc6-dev-amd64 binutils-dev libdwarf-dev

before_script:
- sed -i 's|url = ../|url = https://github.com/darlinghq/|g' .gitmodules
- git submodule update --init --recursive
- mkdir build
- cd build
- cmake .. -DCMAKE_TOOLCHAIN_FILE=../Toolchain.cmake
script:
- make -j $(nproc)
- cd ../src/lkm
- make -j $(nproc)
after_success:
- sudo make install
- cd ../../build
- sudo make install
- darling shell echo "Hello world"
